name = "Databento"
uuid = "a8d7c8e0-6f9a-4b3d-8e2a-1f3c5d6e7f8a"
authors = ["Databento Team"]
version = "0.1.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
CxxWrap = "0.15"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
